#!/bin/bash

on_error() {
  local exit_code=$?
  if [[ $exit_code -ne 0 ]]; then
    $@
  fi
}

abort_on_error() {
  local exit_code=$?
  local message=$1
  if [[ $exit_code -ne 0 ]]; then
    $@
    exit $exit_code
  fi
}

complain_on_error() {
  local exit_code=$?
  local message=$1
  if [[ $exit_code -ne 0 ]]; then
    echo "Error: $message" >&2
  fi
}

complain_and_abort_on_error() {
  local exit_code=$?
  local message=$1
  if [[ $exit_code -ne 0 ]]; then
    echo "Error: $message" >&2
    exit $exit_code
  fi
}

command_exists() {
  command -v "$1" >/dev/null 2>&1
}
