#!/bin/bash
# Cargar nvm
export NVM_DIR="$HOME/.nvm"
# Esto carga nvm
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
# Esto carga nvm bash_completion (opcional, pero recomendado)
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
